# Generated by Django 5.0.6 on 2024-07-18 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_type', models.IntegerField(choices=[(1, 'Other'), (2, 'Heavy Jet'), (3, 'Light Jet'), (4, 'Midsize Jet'), (5, 'Large Cabin'), (6, 'Piston Single'), (7, 'Piston Twin'), (8, 'Super Heavy Jet'), (9, 'Super Light Jet'), (10, 'Super Midsize Jet'), (11, 'Turbo Prop'), (12, 'Helicopter')])),
                ('passenger_capacity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(150)])),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_type', models.IntegerField(choices=[(1, 'Bike'), (2, 'Car')])),
                ('body_type', models.IntegerField(blank=True, choices=[(1, 'Sports'), (2, 'SUV'), (3, 'Sedan'), (4, 'Hatchback'), (5, 'MUV'), (6, 'Compact Sedan'), (7, 'Compact SUV'), (8, 'Convertible'), (9, 'Coupe'), (10, 'Station Wagon'), (11, 'Minivan'), (12, 'Truck')], null=True)),
                ('transmission', models.IntegerField(blank=True, choices=[(1, 'Automatic'), (2, 'Manual')], null=True)),
                ('seating_capacity', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('fuel_type', models.IntegerField(choices=[(1, 'Diesel'), (2, 'Electric'), (3, 'Gas'), (4, 'Hybrid'), (5, 'Natural Gas'), (6, 'Hydrogen'), (7, 'Petrol')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PentHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('societyname', models.CharField(default='')),
                ('bhk', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('covered_area', models.PositiveSmallIntegerField()),
                ('furnishing', models.IntegerField(choices=[(1, 'Semi-furnished'), (2, 'Unfurnished'), (3, 'Furnished')])),
                ('bathrooms', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('facing', models.SmallIntegerField(choices=[(1, 'East'), (2, 'North'), (3, 'North - East'), (4, 'North - West'), (5, 'South'), (6, 'South - East'), (7, 'South - West'), (8, 'West')])),
                ('location', models.IntegerField(choices=[(1, 'Vinewood'), (2, 'South Los Santos'), (3, 'West Vinewood'), (4, 'Paleto Bay'), (5, 'Blaine County'), (6, 'Mission Row'), (7, 'Rockford Hills'), (8, 'Del Perro'), (9, 'Sandy Shores'), (10, 'Los Santos International Airport (LSIA)'), (11, 'Chumash'), (12, 'Davis'), (13, 'East Vinewood'), (14, 'Grapeseed'), (15, 'Other')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penthouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yacht_type', models.IntegerField(choices=[(1, 'Sail'), (2, 'Power')])),
                ('hull_material', models.IntegerField(choices=[(1, 'Aluminum'), (2, 'Composite'), (3, 'Ferro-Cement'), (4, 'Fiberglass'), (5, 'Other'), (6, 'PVC'), (7, 'Steel'), (8, 'Wood'), (9, 'Other')])),
                ('fuel_type', models.IntegerField(choices=[(1, 'Diesel'), (2, 'Electric'), (3, 'Petrol'), (4, 'Other')])),
                ('length', models.SmallIntegerField(default=0)),
                ('beam', models.SmallIntegerField(default=0)),
                ('number_of_engines', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4+')])),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yachts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
