# Generated by Django 5.0.6 on 2024-07-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automobile',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
