# Generated by Django 5.0.6 on 2024-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_aircraft_quantity_automobile_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='plane_type',
            field=models.IntegerField(choices=[(1, 'Helicopter'), (2, 'Heavy Jet'), (3, 'Light Jet'), (4, 'Midsize Jet'), (5, 'Large Cabin'), (6, 'Piston Single'), (7, 'Piston Twin'), (8, 'Super Heavy Jet'), (9, 'Super Light Jet'), (10, 'Super Midsize Jet'), (11, 'Turbo Prop')]),
        ),
        migrations.AlterField(
            model_name='penthouse',
            name='location',
            field=models.IntegerField(choices=[(1, 'Vinewood'), (2, 'South Los Santos'), (3, 'West Vinewood'), (4, 'Paleto Bay'), (5, 'Blaine County'), (6, 'Mission Row'), (7, 'Rockford Hills'), (8, 'Del Perro'), (9, 'Sandy Shores'), (10, 'Los Santos International Airport (LSIA)'), (11, 'Chumash'), (12, 'Davis'), (13, 'East Vinewood'), (14, 'Grapeseed')]),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='fuel_type',
            field=models.IntegerField(choices=[(1, 'Diesel'), (2, 'Electric'), (3, 'Petrol')]),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='hull_material',
            field=models.IntegerField(choices=[(1, 'Aluminum'), (2, 'Composite'), (3, 'Ferro-Cement'), (4, 'Fiberglass'), (5, 'Other'), (6, 'PVC'), (7, 'Steel'), (8, 'Wood')]),
        ),
    ]
