# Generated by Django 5.0.6 on 2024-07-21 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_created_at_penthouse_listed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='plane_type',
            field=models.IntegerField(choices=[(1, 'Helicopter'), (2, 'Heavy Jet'), (3, 'Light Jet'), (4, 'Midsize Jet'), (5, 'Large Cabin'), (6, 'Piston Single'), (7, 'Piston Twin'), (8, 'Super Heavy Jet'), (9, 'Super Light Jet'), (10, 'Super Midsize Jet'), (11, 'Turbo Prop'), (12, 'Other')]),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='body_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Sports'), (2, 'SUV'), (3, 'Sedan'), (4, 'Hatchback'), (5, 'MUV'), (6, 'Compact Sedan'), (7, 'Compact SUV'), (8, 'Convertible'), (9, 'Coupe'), (10, 'Station Wagon'), (11, 'Minivan'), (12, 'Truck'), (13, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='seating_capacity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='penthouse',
            name='location',
            field=models.IntegerField(choices=[(1, 'Vinewood'), (2, 'South Los Santos'), (3, 'West Vinewood'), (4, 'Paleto Bay'), (5, 'Blaine County'), (6, 'Mission Row'), (7, 'Rockford Hills'), (8, 'Del Perro'), (9, 'Sandy Shores'), (10, 'Los Santos International Airport (LSIA)'), (11, 'Chumash'), (12, 'Davis'), (13, 'East Vinewood'), (14, 'Grapeseed'), (15, 'Other')]),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='hull_material',
            field=models.IntegerField(choices=[(1, 'Aluminum'), (2, 'Composite'), (3, 'Ferro-Cement'), (4, 'Fiberglass'), (5, 'Wood'), (6, 'PVC'), (7, 'Steel'), (8, 'Other')]),
        ),
    ]
