# Generated by Django 5.0.6 on 2024-07-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_aircraft_plane_type_alter_automobile_body_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'Yacht'), (2, 'Penthouse'), (3, 'Aircraft'), (4, 'Automobile')])),
            ],
        ),
        migrations.RenameField(
            model_name='penthouse',
            old_name='societyname',
            new_name='house_address',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='AutomobileFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.automobile')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.aircraft')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='features',
            field=models.ManyToManyField(related_name='aircrafts', through='products.AircraftFeature', to='products.feature'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='features',
            field=models.ManyToManyField(related_name='automobiles', through='products.AutomobileFeature', to='products.feature'),
        ),
        migrations.CreateModel(
            name='PenthouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature')),
                ('penthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.penthouse')),
            ],
        ),
        migrations.AddField(
            model_name='penthouse',
            name='features',
            field=models.ManyToManyField(related_name='penthouses', through='products.PenthouseFeature', to='products.feature'),
        ),
        migrations.CreateModel(
            name='YachtFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature')),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.yacht')),
            ],
        ),
        migrations.AddField(
            model_name='yacht',
            name='features',
            field=models.ManyToManyField(related_name='yachts', through='products.YachtFeature', to='products.feature'),
        ),
    ]
