# Generated by Django 5.0.6 on 2024-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_aircraft_description_aircraft_listed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='penthouse',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
