# Generated by Django 5.0.6 on 2024-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_rating_purchases_purchase_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
