# Generated by Django 5.0.6 on 2024-08-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage_main_image_alter_purchases_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
