# Generated by Django 5.0.6 on 2024-07-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
