# Generated by Django 5.0.6 on 2024-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_bank_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_field',
            field=models.DateField(auto_now_add=True),
        ),
    ]
