# Generated by Django 5.0.6 on 2024-07-17 08:23

from django.db import migrations, models
import datetime

def convert_datetime_to_date(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        if isinstance(profile.date_field, datetime.datetime):
            profile.date_field = profile.date_field.date()
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_date_field'),
    ]

    operations = [
        migrations.RunPython(convert_datetime_to_date),
        migrations.AlterField(
            model_name='profile',
            name='date_field',
            field=models.DateField(auto_now_add=True),
        )
    ]
